export const Routes = {
  Home: 'Home',
  Settings: 'Settings',
  Splash: 'Splash',
  Signup: 'Signup',
  Login: 'Login',
  Forgetpassword: 'Forgetpassword',
  Tab: 'Tab',
  Otpverification: 'Otpverification',
  Editprofile: ' Editprofile',
  Createnewpassword: 'Createnewpassword',
  Resetpassword: 'Resetpassword',
  Feedback: 'Feedback',
  GiveFeedback: 'GiveFeedback',
  Addfeedback: 'Addfeedback',
};
